export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const СLEAR_SERVICE_FIELD = "СLEAR_SERVICE_FIELD";
export const SET_SERVICE_FILTER = "SET_SERVICE_FILTER";
